### ISSUE TITLE
This repo doesn't have a license

### ISSUE THREAD

**Issue by dhilton** [ONSdigital/alpha-eq-survey-runner#2]
All ONS repos should have a Crown copyright and MIT license statement in the root of the project.

**Comment by berianjones** [comment]
I agree with you on the need for Copyright and a licence, though why MIT, I would prefer the Apache 2.0, but am open to review this

**Comment by berianjones** [comment]
Sorry wrong button pressed

**Comment by dhilton** [comment]
Having checked with higher powers, the standard GDS license is the one with ONS specific copyright information. Will open a PR to add to all repos.
